name: new-deploy
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: self-hosted
    environment:
      name: dev
    steps:
      - name: Call Share Action from another repository
        uses: Beezzbank/action-lab/.github/actions@main 
        with:
          HOST_IP: ${{ vars.HOST_IP }}

      - name: Check
        run: |
            echo "HOST_IP from Action: $result"